export const experienceConfig = {
  marquee: [
    "Content That Converts",
    "Performance Marketing",
    "Social Growth",
    "Paid Media",
    "Brand Storytelling",
    "Creative Direction",
    "Revenue Systems",
  ],
  story: [
    {
      chapter: "01",
      title: "We decode attention.",
      body: "Every scroll, view, and click is data. We map how your audience moves before we ever launch a campaign.",
    },
    {
      chapter: "02",
      title: "We craft the narrative.",
      body: "From reels to landing pages, every asset is designed to pull people deeper into your brand story.",
    },
    {
      chapter: "03",
      title: "We engineer growth.",
      body: "Paid media, funnels, and content systems working together — not in silos — to compound results.",
    },
  ],
  portfolio: [
    {
      slug: "idfc-first-bank",
      client: "IDFC FIRST Bank",
      category: "Brand Launch",
      metric: "Emerging Banker",
      challenge: "IDFC FIRST Bank required a high-impact recruitment and branding showcase for their Emerging Banker Program to attract top financial talent across India.",
      approach: "Produced a cinematic video story highlighting career acceleration, employee culture, and financial leadership. Created multi-channel video assets and landing page media.",
      results: ["+240% Program Applications", "1.8M Video Impressions", "4.8x Higher Lead Quality"],
      image: "https://6xft9z0vzph7qrfh.public.blob.vercel-storage.com/media/idfc/cover-jYaxUmuyWHMwQXnUAicpcMULOwZWkV.jpg",
      video: "https://6xft9z0vzph7qrfh.public.blob.vercel-storage.com/media/idfc/video-Bt4IUHGUoYCylDoaOkpiO6OCKNI1ji.mp4",
      mediaType: "video" as const,
      aspectRatio: "16/9",
    },
    {
      slug: "quberx-brand-identity",
      client: "Quberx",
      category: "Creative Direction",
      metric: "Brand Identity",
      challenge: "Quberx needed a modern, minimalist brand system and asset library to position themselves as forward-thinking tech innovators.",
      approach: "Engineered custom visual identity guidelines, modern digital interface concepts, and high-converting marketing creative.",
      results: ["+180% Web Engagement", "3.2x Campaign CTR", "Modern Brand Identity System"],
      image: "https://6xft9z0vzph7qrfh.public.blob.vercel-storage.com/media/quberx/cover-qvGLBDtuKOJ9WVQIIa99KUAYOcEFuC.jpeg",
      detailImage: "https://6xft9z0vzph7qrfh.public.blob.vercel-storage.com/media/quberx/detail1-i0R0EHRObjBAXtG81lXirWNgd7Yhzp.jpeg",
      additionalImages: ["https://6xft9z0vzph7qrfh.public.blob.vercel-storage.com/media/quberx/detail1-i0R0EHRObjBAXtG81lXirWNgd7Yhzp.jpeg", "https://6xft9z0vzph7qrfh.public.blob.vercel-storage.com/media/quberx/detail2-chNr2EGehB1oQI4Rq5UoHHWtI0gAyX.jpeg"],
      mediaType: "image" as const,
      aspectRatio: "1/1",
    },
    {
      slug: "adhyaksh-film-shoot",
      client: "Adhyaksh (Bhairava Films)",
      category: "Brand Launch",
      metric: "4.5M Views",
      challenge: "Bhairava Films produced the official announcement shoot for 'Adhyaksh', requiring dynamic promotional posters and high-energy social creative.",
      approach: "Managed full end-to-end creative direction, set design, portrait photography, and promotional rollout across digital channels.",
      results: ["4.5M Announcement Impressions", "+310% Social Share Rate", "Trending Film Teaser"],
      image: "https://6xft9z0vzph7qrfh.public.blob.vercel-storage.com/media/song_1/cover-ig4m42lSOxVxDky1UKzo3QuyWZkt5G.webp",
      detailImage: "https://6xft9z0vzph7qrfh.public.blob.vercel-storage.com/media/song_1/cover-ig4m42lSOxVxDky1UKzo3QuyWZkt5G.webp",
      mediaType: "image" as const,
      aspectRatio: "3/4",
    },
    {
      slug: "danny-pandit-brahmaa",
      client: "Zat Pat Pata Pat Anthem",
      category: "Social Content",
      metric: "6.2M Views",
      challenge: "Building momentum and explosive viral traction for the official anthem launch featuring Danny Pandit and Brahmaa.",
      approach: "Designed punchy social hooks, creative teasers, and multi-format promotional campaigns across Instagram and YouTube.",
      results: ["6.2M Cumulative Views", "45K+ Audio Uses", "+220% Fan Engagement"],
      image: "https://6xft9z0vzph7qrfh.public.blob.vercel-storage.com/media/song_2/cover-ofYGHs0KFj5hBXMqe6lQ9dfsRQAdj0.jpeg",
      detailImage: "https://6xft9z0vzph7qrfh.public.blob.vercel-storage.com/media/song_2/cover-ofYGHs0KFj5hBXMqe6lQ9dfsRQAdj0.jpeg",
      mediaType: "image" as const,
      aspectRatio: "3/4",
    },
    {
      slug: "erik-vinmayi-96",
      client: "Erik & Vinmayi Music - '96'",
      category: "Cinematic Film",
      metric: "3.8M Views",
      challenge: "Creating a nostalgic and emotional visual campaign for the release of the music track '96'.",
      approach: "Crafted evocative visual storytelling, mood photography, and cross-platform campaign strategy tailored for music lovers.",
      results: ["3.8M Track Streams", "+190% Audience Retention", "Featured on Top Playlists"],
      image: "https://6xft9z0vzph7qrfh.public.blob.vercel-storage.com/media/song_3/cover-WRNpDfrTCKIpngYIFVW4DjeWUMk9xa.jpeg",
      detailImage: "https://6xft9z0vzph7qrfh.public.blob.vercel-storage.com/media/song_3/cover-WRNpDfrTCKIpngYIFVW4DjeWUMk9xa.jpeg",
      mediaType: "image" as const,
      aspectRatio: "4/5",
    },
    {
      slug: "commercial-adshoot-series",
      client: "Commercial Youth Series",
      category: "Performance Ads",
      metric: "+180% CTR",
      challenge: "Developing a humorous, relatable commercial series designed to capture Gen-Z and millennial attention on social feeds.",
      approach: "Shot engaging short-form narratives with high-contrast color grading, scroll-stopping hooks, and shareable dialogue.",
      results: ["5.1M Organic Views", "8.4x Share Rate", "+140% Brand Search Lift"],
      image: "https://6xft9z0vzph7qrfh.public.blob.vercel-storage.com/media/song_4/cover-AEeKQ8e0uqPS51YwLndLlqF8T51ON1.jpeg",
      detailImage: "https://6xft9z0vzph7qrfh.public.blob.vercel-storage.com/media/song_4/cover-AEeKQ8e0uqPS51YwLndLlqF8T51ON1.jpeg",
      mediaType: "image" as const,
      aspectRatio: "4/5",
    },
  ],
  reels: [
    {
      title: "About Bhairava Media",
      views: "4.8M Views",
      gradient: "from-violet-500 via-fuchsia-500 to-orange-400",
      videoId: "1w4EP_CPVp0",
    },
    {
      title: "How Bhairava Media Drives Brand Impact",
      views: "6.2M Views",
      gradient: "from-cyan-400 via-blue-500 to-indigo-600",
      videoId: "QbUl8Bfme9A",
    },
  ],
  metrics: [
    {
      label: "Revenue Generated",
      value: 4.5,
      prefix: "₹",
      suffix: "Cr+",
      span: "col-span-2 row-span-2",
    },
    {
      label: "Views Delivered",
      value: 120,
      suffix: "M+",
      span: "col-span-1 row-span-1",
    },
    {
      label: "Average ROAS",
      value: 400,
      suffix: "%",
      span: "col-span-1 row-span-1",
    },
    {
      label: "Brands Scaled",
      value: 100,
      suffix: "+",
      span: "col-span-1 row-span-1",
    },
    {
      label: "Campaigns Launched",
      value: 850,
      suffix: "+",
      span: "col-span-1 row-span-1",
    },
    {
      label: "Client Retention",
      value: 94,
      suffix: "%",
      span: "col-span-2 row-span-1",
    },
  ],
};
